services:
  postgresdb:
    image: postgres:14.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT"
    volumes:
      - db:/var/lib/postgres
volumes:
  db:
